using System.Text.Json.Serialization;

namespace WebsiteBuilder.Core.Models;

/// <summary>
/// Metadata for a file managed inside a folder-based project's <c>Assets/</c>
/// directory. The stored name is generated by the application; source paths are
/// never persisted in the project document.
/// </summary>
public sealed class ProjectAsset
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = Guid.NewGuid().ToString("N");

    /// <summary>Sanitized display name derived from the imported source file.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = "Asset";

    /// <summary>Application-controlled file name stored under <c>Assets/</c>.</summary>
    [JsonPropertyName("storedFileName")]
    public string StoredFileName { get; set; } = string.Empty;

    /// <summary>Portable project-relative path, always using forward slashes.</summary>
    [JsonPropertyName("relativePath")]
    public string RelativePath { get; set; } = string.Empty;

    /// <summary>High-level category such as Image, Video, Audio, Font, or Document.</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = AssetKinds.Document;

    /// <summary>Validated media type inferred from both extension and file content.</summary>
    [JsonPropertyName("mediaType")]
    public string MediaType { get; set; } = "application/octet-stream";

    [JsonPropertyName("sizeBytes")]
    public long SizeBytes { get; set; }

    /// <summary>Lowercase SHA-256 digest of the stored bytes.</summary>
    [JsonPropertyName("sha256")]
    public string Sha256 { get; set; } = string.Empty;

    [JsonPropertyName("importedUtc")]
    public DateTimeOffset ImportedUtc { get; set; } = DateTimeOffset.UtcNow;
}

/// <summary>Stable asset category values persisted in Project JSON.</summary>
public static class AssetKinds
{
    public const string Image = "Image";
    public const string Svg = "SVG";
    public const string Icon = "Icon";
    public const string Video = "Video";
    public const string Audio = "Audio";
    public const string Font = "Font";
    public const string Document = "Document";
}
