using System.Net;
using System.Text;
using WebsiteBuilder.Core.Models;
using WebsiteBuilder.Core.Validation;

namespace WebsiteBuilder.CodeGen;

/// <summary>
/// Emits a static HTML5 + CSS + JS site from a <see cref="Project"/>. The canonical
/// model positions elements absolutely within a page frame, so the export mirrors
/// that: a centred page wrapper with absolutely-positioned descendants. Styling and
/// class names come from the shared <see cref="WebStyleSheet"/> (deduped appearance
/// classes + per-element geometry + responsive media queries). Each page becomes a
/// <c>{route}.html</c> file; all pages share one stylesheet and script.
/// </summary>
public sealed class HtmlCodeGenerator : ICodeGenerator
{
    /// <summary>Frame width used when the base breakpoint has no explicit bound.</summary>
    public const int DefaultFrameWidth = WebStyleSheet.DefaultFrameWidth;

    private const string StylesheetPath = "css/styles.css";
    private const string ScriptPath = "js/main.js";

    /// <inheritdoc />
    public CodeGenTarget Target => CodeGenTarget.StaticHtml;

    /// <inheritdoc />
    public IReadOnlyList<GeneratedFile> Generate(Project project)
    {
        ArgumentNullException.ThrowIfNull(project);
        ProjectValidator.ValidateAndThrow(project);

        if (project.Pages.Count == 0)
        {
            return Array.Empty<GeneratedFile>();
        }

        var sheet = WebStyleSheet.Build(project);

        var files = new List<GeneratedFile>();
        foreach (var page in project.Pages)
        {
            files.Add(new GeneratedFile($"{WebStyleSheet.FileStem(page)}.html", BuildHtml(project, page, sheet)));
        }

        files.Add(new GeneratedFile(StylesheetPath, sheet.Css));
        files.Add(new GeneratedFile(ScriptPath, BuildJs()));
        return files;
    }

    private static string BuildJs() =>
        "// Generated by Likha — Website Builder.\n" +
        "(function () {\n" +
        "  \"use strict\";\n" +
        "  document.addEventListener(\"DOMContentLoaded\", function () {\n" +
        "    // Interactive behaviours (tabs, accordions, modals, forms…) are emitted\n" +
        "    // here as those components are added to the project.\n" +
        "  });\n" +
        "})();\n";

    private static string BuildHtml(Project project, Page page, WebStyleSheet sheet)
    {
        var sb = new StringBuilder();
        var title = WebUtility.HtmlEncode($"{page.Name} — {project.Name}");
        var routeDepth = WebStyleSheet.FileStem(page).Count(character => character == '/');
        var relativePrefix = string.Concat(Enumerable.Repeat("../", routeDepth));

        sb.Append("<!DOCTYPE html>\n");
        sb.Append("<html lang=\"en\">\n");
        sb.Append("<head>\n");
        sb.Append("  <meta charset=\"utf-8\">\n");
        sb.Append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        sb.Append($"  <title>{title}</title>\n");
        sb.Append($"  <link rel=\"stylesheet\" href=\"{relativePrefix}{StylesheetPath}\">\n");
        sb.Append($"  <script src=\"{relativePrefix}{ScriptPath}\" defer></script>\n");
        sb.Append("</head>\n");
        sb.Append("<body>\n");
        AppendElement(sb, page.Root, depth: 1, rootClass: WebStyleSheet.RootClass(page), sheet);
        sb.Append("</body>\n");
        sb.Append("</html>\n");
        return sb.ToString();
    }

    private static void AppendElement(StringBuilder sb, ElementNode node, int depth, string? rootClass, WebStyleSheet sheet)
    {
        var isRoot = rootClass is not null;
        var indent = new string(' ', depth * 2);
        var tag = HtmlTags.TagFor(node.Type);
        var className = isRoot ? rootClass! : sheet.ElementClass(node);
        var attributes = BuildAttributes(node, className);

        if (HtmlTags.IsVoid(tag))
        {
            sb.Append(indent).Append('<').Append(tag).Append(attributes).Append(">\n");
            return;
        }

        sb.Append(indent).Append('<').Append(tag).Append(attributes).Append('>');

        var hasText = !string.IsNullOrEmpty(node.Text);
        var hasChildren = node.Children.Count > 0;

        if (hasText)
        {
            sb.Append(WebUtility.HtmlEncode(node.Text));
        }

        if (hasChildren)
        {
            sb.Append('\n');
            foreach (var child in node.Children)
            {
                AppendElement(sb, child, depth + 1, rootClass: null, sheet);
            }

            sb.Append(indent);
        }

        sb.Append("</").Append(tag).Append(">\n");
    }

    private static string BuildAttributes(ElementNode node, string className)
    {
        var sb = new StringBuilder();
        sb.Append(" class=\"").Append(className).Append('"');

        foreach (var (name, value) in node.Attributes)
        {
            if (!ProjectContentPolicy.IsSafeHtmlAttribute(name, value))
            {
                continue;
            }

            sb.Append(' ').Append(name).Append("=\"").Append(WebUtility.HtmlEncode(value)).Append('"');
        }

        return sb.ToString();
    }

}
