using System.Globalization;
using System.Text;
using WebsiteBuilder.Core.Models;

namespace WebsiteBuilder.CodeGen;

/// <summary>
/// The shared stylesheet for a project, used by both the static-HTML and React
/// generators so they emit identical CSS and matching class names. Appearance
/// (the per-element style map) is de-duplicated into reusable classes (<c>.s1</c>,
/// <c>.s2</c>…); each element keeps its own geometry rule; responsive overrides
/// become desktop-first <c>@media</c> blocks.
/// </summary>
public sealed class WebStyleSheet
{
    /// <summary>Frame width used when the base breakpoint has no explicit bound.</summary>
    public const int DefaultFrameWidth = 1440;

    private readonly IReadOnlyDictionary<string, string> _appearanceByElement;

    private WebStyleSheet(string css, IReadOnlyDictionary<string, string> appearanceByElement)
    {
        Css = css;
        _appearanceByElement = appearanceByElement;
    }

    /// <summary>The complete stylesheet text.</summary>
    public string Css { get; }

    /// <summary>A non-root element's combined class: its geometry class plus any shared appearance class.</summary>
    public string ElementClass(ElementNode node)
    {
        var geometry = "wb-" + Sanitize(node.Id);
        return _appearanceByElement.TryGetValue(node.Id, out var appearance)
            ? $"{geometry} {appearance}"
            : geometry;
    }

    /// <summary>A page root's class: the shared frame plus a per-page class when the root has styles.</summary>
    public static string RootClass(Page page) =>
        page.Root.Styles.Count > 0 || page.Root.ResponsiveStyles.Values.Any(layer => layer.Count > 0)
            ? $"wb-page wb-page-{Sanitize(FileStem(page))}"
            : "wb-page";

    /// <summary>Output file stem for a page (its route, defaulting to "index").</summary>
    public static string FileStem(Page page) =>
        string.IsNullOrWhiteSpace(page.Route) ? "index" : page.Route.Trim().Trim('/');

    /// <summary>Turns an element id into a CSS-class-safe suffix.</summary>
    public static string Sanitize(string id)
    {
        if (string.IsNullOrEmpty(id))
        {
            return "el";
        }

        var chars = id.Select(c => char.IsLetterOrDigit(c) || c is '-' or '_' ? c : '-').ToArray();
        return new string(chars);
    }

    /// <summary>Builds the project-wide stylesheet and the element→appearance-class map.</summary>
    public static WebStyleSheet Build(Project project)
    {
        ArgumentNullException.ThrowIfNull(project);

        var registry = new StyleClassRegistry();
        foreach (var page in project.Pages)
        {
            foreach (var child in page.Root.Children)
            {
                RegisterStyles(registry, child);
            }
        }

        var css = BuildCss(project, registry);
        return new WebStyleSheet(css, registry.AppearanceByElement);
    }

    private static void RegisterStyles(StyleClassRegistry registry, ElementNode node)
    {
        registry.Register(node);
        foreach (var child in node.Children)
        {
            RegisterStyles(registry, child);
        }
    }

    private static string BuildCss(Project project, StyleClassRegistry styles)
    {
        var sb = new StringBuilder();
        sb.Append("/* Generated by Likha — Website Builder. Do not edit by hand. */\n");
        sb.Append("*, *::before, *::after { box-sizing: border-box; }\n");
        sb.Append("html, body { margin: 0; padding: 0; }\n");

        if (project.Variables.Count > 0)
        {
            sb.Append("\n:root {\n");
            foreach (var (name, value) in project.Variables)
            {
                var prop = name.StartsWith("--", StringComparison.Ordinal) ? name : "--" + name;
                sb.Append("  ").Append(prop).Append(": ").Append(value).Append(";\n");
            }

            sb.Append("}\n");
        }

        // Shared, de-duplicated appearance classes (project-wide).
        foreach (var (className, declarations) in styles.Classes)
        {
            sb.Append('\n').Append('.').Append(className).Append(" {\n");
            foreach (var (name, value) in declarations)
            {
                sb.Append("  ").Append(name).Append(": ").Append(value).Append(";\n");
            }

            sb.Append("}\n");
        }

        // Shared page-frame rule, then per-page root styles (only when a root has any).
        AppendPageFrameRule(sb, FrameWidth(project));
        foreach (var page in project.Pages)
        {
            if (page.Root.Styles.Count > 0)
            {
                sb.Append("\n.wb-page-").Append(Sanitize(FileStem(page))).Append(" {\n");
                foreach (var (name, value) in page.Root.Styles)
                {
                    sb.Append("  ").Append(name).Append(": ").Append(value).Append(";\n");
                }

                sb.Append("}\n");
            }
        }

        // Per-element geometry rules across all pages (after appearance classes so
        // geometry wins any same-specificity tie on layout properties).
        foreach (var page in project.Pages)
        {
            foreach (var child in page.Root.Children)
            {
                AppendGeometryRules(sb, child);
            }
        }

        AppendMediaQueries(sb, project, project.Pages);
        return sb.ToString();
    }

    private static void AppendMediaQueries(StringBuilder sb, Project project, IEnumerable<Page> pages)
    {
        var pageList = pages.ToList();
        var breakpoints = project.Breakpoints
            .Where(b => !b.IsBase && b.MaxWidth > 0)
            .OrderByDescending(b => b.MaxWidth)
            .ToList();

        foreach (var bp in breakpoints)
        {
            var blocks = new List<(string Selector, IReadOnlyList<KeyValuePair<string, string>> Declarations)>();
            foreach (var page in pageList)
            {
                CollectOverrides(
                    page.Root,
                    bp.Id,
                    isRoot: true,
                    rootSelector: ".wb-page-" + Sanitize(FileStem(page)),
                    blocks);
            }

            if (blocks.Count == 0)
            {
                continue;
            }

            sb.Append("\n@media (max-width: ")
              .Append(bp.MaxWidth.ToString(CultureInfo.InvariantCulture))
              .Append("px) {\n");

            foreach (var (selector, declarations) in blocks)
            {
                sb.Append("  ").Append(selector).Append(" {\n");
                foreach (var (name, value) in declarations)
                {
                    sb.Append("    ").Append(name).Append(": ").Append(value).Append(";\n");
                }

                sb.Append("  }\n");
            }

            sb.Append("}\n");
        }
    }

    private static void CollectOverrides(
        ElementNode node,
        string breakpointId,
        bool isRoot,
        string rootSelector,
        List<(string Selector, IReadOnlyList<KeyValuePair<string, string>> Declarations)> blocks)
    {
        if (node.ResponsiveStyles.TryGetValue(breakpointId, out var overrides) && overrides.Count > 0)
        {
            var selector = isRoot ? rootSelector : ".wb-" + Sanitize(node.Id);
            var declarations = overrides.OrderBy(kv => kv.Key, StringComparer.Ordinal).ToList();
            blocks.Add((selector, declarations));
        }

        foreach (var child in node.Children)
        {
            CollectOverrides(child, breakpointId, isRoot: false, rootSelector, blocks);
        }
    }

    private static void AppendPageFrameRule(StringBuilder sb, int frameWidth)
    {
        sb.Append("\n.wb-page {\n");
        sb.Append("  position: relative;\n");
        sb.Append("  width: 100%;\n");
        sb.Append("  max-width: ").Append(frameWidth.ToString(CultureInfo.InvariantCulture)).Append("px;\n");
        sb.Append("  margin: 0 auto;\n");
        sb.Append("  min-height: 100vh;\n");
        sb.Append("}\n");
    }

    private static void AppendGeometryRules(StringBuilder sb, ElementNode node)
    {
        sb.Append("\n.wb-").Append(Sanitize(node.Id)).Append(" {\n");
        sb.Append("  position: absolute;\n");
        sb.Append("  left: ").Append(Px(node.X)).Append(";\n");
        sb.Append("  top: ").Append(Px(node.Y)).Append(";\n");
        if (node.Width > 0)
        {
            sb.Append("  width: ").Append(Px(node.Width)).Append(";\n");
        }

        if (node.Height > 0)
        {
            sb.Append("  height: ").Append(Px(node.Height)).Append(";\n");
        }

        if (node.Rotation != 0)
        {
            sb.Append("  transform: rotate(")
              .Append(node.Rotation.ToString("0.##", CultureInfo.InvariantCulture))
              .Append("deg);\n");
        }

        if (node.Hidden)
        {
            sb.Append("  display: none;\n");
        }

        sb.Append("}\n");

        foreach (var child in node.Children)
        {
            AppendGeometryRules(sb, child);
        }
    }

    private static int FrameWidth(Project project)
    {
        var baseBp = project.Breakpoints.FirstOrDefault(b => b.IsBase) ?? project.Breakpoints.FirstOrDefault();
        return baseBp is { MaxWidth: > 0 } ? baseBp.MaxWidth : DefaultFrameWidth;
    }

    private static string Px(double value) => value.ToString("0.##", CultureInfo.InvariantCulture) + "px";

    /// <summary>
    /// Collects distinct appearance declaration-sets across elements and assigns each
    /// a stable shared class name (s1, s2, …) in first-seen order. Elements with no
    /// styles get no class.
    /// </summary>
    private sealed class StyleClassRegistry
    {
        private readonly Dictionary<string, string> _classByKey = new(StringComparer.Ordinal);
        private readonly Dictionary<string, string> _classByElement = new(StringComparer.Ordinal);
        private readonly List<(string ClassName, IReadOnlyList<KeyValuePair<string, string>> Declarations)> _classes = new();

        public IReadOnlyList<(string ClassName, IReadOnlyList<KeyValuePair<string, string>> Declarations)> Classes => _classes;

        public IReadOnlyDictionary<string, string> AppearanceByElement => _classByElement;

        public void Register(ElementNode node)
        {
            if (node.Styles.Count == 0)
            {
                return;
            }

            var declarations = node.Styles
                .OrderBy(kv => kv.Key, StringComparer.Ordinal)
                .ToList();

            var key = string.Join(";", declarations.Select(kv => $"{kv.Key}:{kv.Value}"));
            if (!_classByKey.TryGetValue(key, out var className))
            {
                className = "s" + (_classes.Count + 1).ToString(CultureInfo.InvariantCulture);
                _classByKey[key] = className;
                _classes.Add((className, declarations));
            }

            _classByElement[node.Id] = className;
        }
    }
}
